# Generated by Django 5.1.7 on 2025-05-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
