# Generated by Django 5.1.7 on 2025-05-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_livro_options_alter_reserva_data_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
