# Generated by Django 5.1.7 on 2025-05-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_reserva_ativo_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.IntegerField(),
        ),
    ]
