# Generated by Django 5.1.7 on 2025-05-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_livro_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade_disponivel',
            field=models.IntegerField(default=1),
        ),
    ]
