# Generated by Django 5.1.7 on 2025-05-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_livro_quantidade_livro_quantidade_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
    ]
